// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnPbs2MbF8aLTIVngK3AB2gkozLhXa53E',
    appId: '1:777103653371:web:769b49208ee1f6a951b35e',
    messagingSenderId: '777103653371',
    projectId: 'invoicereader-70363',
    authDomain: 'invoicereader-70363.firebaseapp.com',
    storageBucket: 'invoicereader-70363.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7wiP3rykFf_suFP7Y6PBnnog05_urB0',
    appId: '1:777103653371:android:0aa75420d50b352051b35e',
    messagingSenderId: '777103653371',
    projectId: 'invoicereader-70363',
    storageBucket: 'invoicereader-70363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5dmFsF-FJo7VIVYpPDoTJEni_hRhxnBw',
    appId: '1:777103653371:ios:a449b2c33dee6a6551b35e',
    messagingSenderId: '777103653371',
    projectId: 'invoicereader-70363',
    storageBucket: 'invoicereader-70363.firebasestorage.app',
    iosBundleId: 'com.icecreamparlour.invoicereport.invoicereport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5dmFsF-FJo7VIVYpPDoTJEni_hRhxnBw',
    appId: '1:777103653371:ios:a449b2c33dee6a6551b35e',
    messagingSenderId: '777103653371',
    projectId: 'invoicereader-70363',
    storageBucket: 'invoicereader-70363.firebasestorage.app',
    iosBundleId: 'com.icecreamparlour.invoicereport.invoicereport',
  );

}